netty:
  server:
    tcp-port: 9009
    user-id: 123456
    password: test809


spring:
  application:
    name: providence-service-jt809
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/jt809?serverTimezone=Hongkong&useSSL=false&useUnicode=true&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: 2a10r45GloxD!@
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
logging:
  level:
    com.ysy.jt809: trace